export { default as Home } from './Home';
export { default as Search } from './Search';
export { default as Activity } from './Activity';
export { default as CreateThread } from './CreateThread';
export { default as Profile } from './Profile';
export { default as Settings } from './Settings';
export { default as About } from './About';
export { default as Account } from './Account';
export { default as Follows } from './Follows';
export { default as Help } from './Help';
export { default as Language } from './Language';
export { default as Notifications } from './Notifications';
export { default as Privacy } from './Privacy';
export { default as YourLikes } from './YourLikes'
